lib/chess_club_web/router.ex
defmodule ChessClubWeb.Router do
  use ChessClubWeb, :router

  import ChessClubWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
    plug :put_user_token # internal plug at the bottom
  end

  pipeline :api do
    plug :accepts, ["json"]
  end


  scope "/", ChessClubWeb do
    pipe_through :browser

    get "/", HomeController, :index
  end



  # Other scopes may use custom stacks.
  # scope "/api", ChessClubWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: ChessClubWeb.Telemetry
    end
  end

  ## Authentication routes

  scope "/", ChessClubWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", ChessClubWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", ChessClubWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :confirm
  end

  scope "/", ChessClubWeb do
    pipe_through [:browser]

    resources "/rooms", RoomController

  end

  scope "/", ChessClubWeb do
    pipe_through [:browser]

    get "/game/:game_id", GameController, :new

  end





  # Internal Plugs
  defp put_user_token(conn, _) do
    if current_user = conn.assigns[:current_user] do
      token = Phoenix.Token.sign(conn, "user socket",  "#{current_user.firstname} #{current_user.lastname}")
      assign(conn, :user_token, token)
    else
      conn
    end
  end

end

lib/chess_club_web/controllers/home_controller.ex
defmodule ChessClubWeb.HomeController do
  use ChessClubWeb, :controller

  alias ChessClub.RoomContext

  def index(conn, _params) do
    rooms = RoomContext.list_rooms()
    render(conn, "index.html", rooms: rooms)
  end
end

lib/chess_club_web/views/home_view.ex
defmodule ChessClubWeb.HomeView do
  use ChessClubWeb, :view
end

lib/chess_club_web/templates/home/global_notifications.html.eex
<h4>Latest Notifications</h4>
<div class="gnotbox">
    <ul id="global-notifications">
        <li>
            No Notifications!
        </li>
    </ul>
</div>

lib/chess_club_web/templates/home/index.html.eex
<section class="row">
    <%= render ChessClubWeb.SharedView, "_quick_commands_menu.html", assigns %>
</section>


<section class="row">
  <%= render "online_users.html", conn: @conn %>


  <section class="column column-40">
    <%= render "news_feed.html", conn: @conn %>
  </section>


  <section class="column column-25">
    <%= render "global_notifications.html", conn: @conn %>
  </section>

  <section class="column column-20">
    <h4 style="margin-bottom:0;padding-bottom:0">Rooms
    <span style="float:right">
      <a style="text-align:right" href="<%= Routes.room_path(@conn, :new) %>" >create your room</a>
    </span>
    </h4>

    <div class="room-list">
      <%= for room <- @rooms do %>
      <a href="<%= Routes.room_path(@conn, :show, room) %>">
        <div class="room-link">
          <%= room.name %>
        </div>
      </a>

      <% end %>
    </div>


  </section>

</section>

<script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/console.js") %>"></script>
<script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/global_notifications.js") %>"></script>