lib/chess_club_web/router.ex
defmodule ChessClubWeb.Router do
  use ChessClubWeb, :router

  import ChessClubWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
    plug :put_user_token # internal plug at the bottom
  end

  pipeline :api do
    plug :accepts, ["json"]
  end


  scope "/", ChessClubWeb do
    pipe_through :browser

    get "/", HomeController, :index
  end



  # Other scopes may use custom stacks.
  # scope "/api", ChessClubWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: ChessClubWeb.Telemetry
    end
  end

  ## Authentication routes

  scope "/", ChessClubWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", ChessClubWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", ChessClubWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :confirm
  end

  scope "/", ChessClubWeb do
    pipe_through [:browser]

    resources "/rooms", RoomController

  end

  scope "/", ChessClubWeb do
    pipe_through [:browser]

    get "/game/:game_id", GameController, :new

  end





  # Internal Plugs
  defp put_user_token(conn, _) do
    if current_user = conn.assigns[:current_user] do
      token = Phoenix.Token.sign(conn, "user socket",  "#{current_user.firstname} #{current_user.lastname}")
      assign(conn, :user_token, token)
    else
      conn
    end
  end

end

lib/chess_club_web/views/shared_view.ex
defmodule ChessClubWeb.SharedView do
  use ChessClubWeb, :view
end

lib/chess_club_web/templates/shared/_game_chat.html.eex
<section class="column column-20">
    <h4> <i style="color:green" class="fa fa-signal"></i> Now Playing: <span id="online-members-count" style="font-weight:bold">----</span></h4>
    <div style="width: 200px; height: 400px; overflow-y: auto; width:100%">
        <ul id="members-list" style="list-style-type:none;">

        </ul>
    </div>

</section>

lib/chess_club_web/templates/shared/_global_notifications.html.eex
<h4>Latest Notifications</h4>
<div class="gnotbox">
    <ul id="global-notifications">
        <li>
            No Notifications!
        </li>
    </ul>
</div>

lib/chess_club_web/templates/shared/_quick_commands_menu.html.eex
<div class="quick-commands" style="margin-bottom: 75px">
    <strong>Quick Commands:</strong>
    <button id="1min">1-minute</button>
    <button id="3min">3-minute</button>
    <button id="5min" >5-minute</button>
    <button id="10min">10-minute</button>
</div>

<!-- The Modal -->
<div id="myModal" class="modal">

    <!-- Modal content -->
    <div class="modal-content">
        <span class="close">&times;</span>
        <p>body</p>
    </div>

</div>

lib/chess_club_web/templates/shared/header.html.eex
<header>
    <section class="container">
        <nav role="navigation">
            <ul>
                <%= if @current_user do %>
                <li><%= @current_user.email %></li>
                <li><%= link "Settings", to: Routes.user_settings_path(@conn, :edit) %></li>
                <li><%= link "Log out", to: Routes.user_session_path(@conn, :delete), method: :delete %></li>
                <% else %>
                <li><%= link "Register", to: Routes.user_registration_path(@conn, :new) %></li>
                <li><%= link "Log in", to: Routes.user_session_path(@conn, :new) %></li>
                <% end %>
            </ul>
        </nav>
        <a href="<%= Routes.home_path(@conn, :index) %>" class="phx-logo">
            <img src="<%= Routes.static_path(@conn, "/images/logo.png") %>" alt="Chess Club Logo"/>
        </a>
    </section>
</header>