lib/chess_club_web/router.ex
defmodule ChessClubWeb.Router do
  use ChessClubWeb, :router

  import ChessClubWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
    plug :put_user_token # internal plug at the bottom
  end

  pipeline :api do
    plug :accepts, ["json"]
  end


  scope "/", ChessClubWeb do
    pipe_through :browser

    get "/", HomeController, :index
  end



  # Other scopes may use custom stacks.
  # scope "/api", ChessClubWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: ChessClubWeb.Telemetry
    end
  end

  ## Authentication routes

  scope "/", ChessClubWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", ChessClubWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", ChessClubWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :confirm
  end

  scope "/", ChessClubWeb do
    pipe_through [:browser]

    resources "/rooms", RoomController

  end

  scope "/", ChessClubWeb do
    pipe_through [:browser]

    get "/game/:game_id", GameController, :new

  end





  # Internal Plugs
  defp put_user_token(conn, _) do
    if current_user = conn.assigns[:current_user] do
      token = Phoenix.Token.sign(conn, "user socket",  "#{current_user.firstname} #{current_user.lastname}")
      assign(conn, :user_token, token)
    else
      conn
    end
  end

end

lib/chess_club_web/controllers/user_session_controller.ex
defmodule ChessClubWeb.UserSessionController do
  use ChessClubWeb, :controller

  alias ChessClub.AccountsContext
  alias ChessClubWeb.UserAuth

  def new(conn, _params) do
    render(conn, "new.html", error_message: nil)
  end

  def create(conn, %{"user" => user_params}) do
    %{"email" => email, "password" => password} = user_params

    if user = AccountsContext.get_user_by_email_and_password(email, password) do
      UserAuth.log_in_user(conn, user, user_params)
    else
      render(conn, "new.html", error_message: "Invalid email or password")
    end
  end

  def delete(conn, _params) do
    conn
    |> put_flash(:info, "Logged out successfully.")
    |> UserAuth.log_out_user()
  end
end

lib/chess_club_web/views/user_session_view.ex
defmodule ChessClubWeb.UserSessionView do
  use ChessClubWeb, :view
end

lib/chess_club_web/templates/user_session/new.html.eex
<div class="row">
    <div class="column column-25 card" style="margin:0 auto; padding:0">

        <h2>Log in</h2>

        <%= form_for @conn, Routes.user_session_path(@conn, :create), [as: :user], fn f -> %>
          <%= if @error_message do %>
            <div class="alert alert-danger">
              <p><%= @error_message %></p>
            </div>
          <% end %>

          <%= label f, :email %>
          <%= email_input f, :email, required: true %>

          <%= label f, :password %>
          <%= password_input f, :password, required: true %>

          <%= label f, :remember_me, "Keep me logged in for 60 days" %>
          <%= checkbox f, :remember_me %>

          <div>
            <%= submit "Log in" %>
          </div>
        <% end %>

        <p>
          <%= link "Register", to: Routes.user_registration_path(@conn, :new) %> |
          <%= link "Forgot your password?", to: Routes.user_reset_password_path(@conn, :new) %>
        </p>
    </div>
</div>